In [1]:
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
encoder = LabelEncoder()
df['alive'] = encoder.fit_transform(df['alive'])

In [4]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,0,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,1,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,1,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,1,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,0,True

In [5]:
df = df[['age', 'fare', 'alive']]
df

      age     fare  alive
0    22.0   7.2500      0
1    38.0  71.2833      1
2    26.0   7.9250      1
3    35.0  53.1000      1
4    35.0   8.0500      0
..    ...      ...    ...
886  27.0  13.0000      0
887  19.0  30.0000      1
888   NaN  23.4500      0
889  26.0  30.0000      1
890  32.0   7.7500      0

[891 rows x 3 columns]

In [7]:
X = df.iloc[:,0:2]
y = df.iloc[:,-1]

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,y,random_state=42 , )